version: '3'
services:
  wordpress:
    image: wordpress
    ports:
    - 8081:80
    environment:
    - WORDPRESS_DB_USER=root
    - WORDPRESS_DB_PASSWORD=password
    - WORDPRESS_DB_HOST=mysql
    - WORDPRESS_DB_NAME=info_p2pu_org_1
    depends_on:
    - mysql
    volumes:
    - .:/var/www/html/wp-content/themes/p2pu-eighteen

  mysql:
    image: mysql:5.7
    environment:
    - MYSQL_ROOT_PASSWORD=password
